const secretKeys = {
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:"pk_live_51NQYPyAsnalb3hUMicApUwxtaCMDtBoPLadNfMq6J4xG9ulNH5miiczExQrX5RJvFXJFTMcByPQPZXYbNHhlObec000HC3RaW3",

   STRIPE_SECRET_KEY:"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"
}
module.exports = secretKeys